#include "cgApplication.h"			//pApplication->StopApplication()
#include "fenetrecamera.h"			//pFenetreCamera
#include "fenetresetting.h"			//pFenetreSetting
#include "fenetredesignateur.h"		//pFenetreDesignateur
#include "fenetretransformation.h"	//pFenetreTransformation
#include "fenetrelumiere.h"			//pFenetreLumiere
#include "fenetreanimation.h"		//pFenetreanimation

extern cgApplication* pApplication;		//Pointeur sur l'application
extern FenetrePrincipale* pFenAff3D;
extern FenetreCamera* pFenetreCamera;
extern FenetreSetting* pFenetreSetting;
extern FenetreDesignateur* pFenetreDesignateur;
extern FenetreTransformation* pFenetreTransformation;
extern FenetreLumiere* pFenetreLumiere;
extern FenetreAnimation* pFenetreAnimation;
